const opener = "@Boiled-Autogenerated Code";
const closer = "@Boiled-Complete";

exports.getRegExOpenTag = function(){
  var re = new RegExp(opener,"g");
  return re;
}
exports.getRegExClosedTag = function(){
  var re = new RegExp(closer,"g");
  return re;
}

exports.genOpenTag = function(opts){

  let o = gen_parseOpts(opts);

  var s = o.lb;
  s    += o.ps + '/*';
  s    += opener;
  s    += '*/' + "\n";
  return s;
}
exports.genClosedTag = function(opts){

  let o = gen_parseOpts(opts);

  var s = o.lb;
  s    += o.ps + '/*';
  s    += closer;
  s    += '*/' + "\n";
  return s;
}



gen_parseOpts = function(options){

  let o = require('../../commons/options').getCurrent();
  options = options || {};

  let ps = '';
  let depth = options.depth || 0;
  for(var i = 0; i < depth; i++){
    ps += '    ';
  }

  let lb = "";
  let lbct = options.lb || 0;
  for(var i = 1; i<lbct; i++ ){
    lb += "\n";
  }

  return {
    ps : ps,
    lb : lb,
    nl : o.nl,
  }
}
