//@Boil(classmaker|defOne)
//@Boil(classMaker|defTwo)

/*@Boiled-Autogenerated Code*/
export interface TestIOne {

    field1 : Array<string>;
    field2 : any;
}
export interface TestITwo {

    field1 : string;
    field2 : number;
}
/*@Boiled-Complete*/
