const opener = "@Boiled-Autogenerated Code";
const closer = "@Boiled-Complete";

exports.genOpenTag = function(){

  var s = '/*'
  s    += opener;
  s    += '*/' + "\n";
  return s;
}
exports.genClosedTag = function(){

  var s = '/*'
  s    += closer;
  s    += '*/' + "\n";
  return s;
}
exports.getRegExOpenTag = function(){
  var re = new RegExp(opener,"g");
  return re;
}
exports.getRegExClosedTag = function(){
  var re = new RegExp(closer,"g");
  return re;
}
