//@Boil(getters)
//@Boil(setters)
export class TestClassForGetSet {

    _field1: Array<string>;
    _field2: Array<number>;
    _field3: Array<Date>;
    _field4: Array<string>;
    _filed5: string;
    _field6: string;
    _field7: string;

    /*@Boiled-Autogenerated Code*/
    public get field1() : Array<string>{
        return this._field1;
    }
    public get field2() : Array<number>{
        return this._field2;
    }
    public get field3() : Array<Date>{
        return this._field3;
    }
    public get field4() : Array<string>{
        return this._field4;
    }
    public get filed5() : string{
        return this._filed5;
    }
    public get field6() : string{
        return this._field6;
    }
    public get field7() : string{
        return this._field7;
    }
    public set field1(field1 : Array<string>){
        this._field1=field1;
    }
    public set field2(field2 : Array<number>){
        this._field2=field2;
    }
    public set field3(field3 : Array<Date>){
        this._field3=field3;
    }
    public set field4(field4 : Array<string>){
        this._field4=field4;
    }
    public set filed5(filed5 : string){
        this._filed5=filed5;
    }
    public set field6(field6 : string){
        this._field6=field6;
    }
    public set field7(field7 : string){
        this._field7=field7;
    }
    /*@Boiled-Complete*/
}
